### ISSUE TITLE
Update QUnit Tests 

### ISSUE THREAD

**Issue by jrmartin** [openworm/org.geppetto.frontend#306]
After all refactoring in datamanager branch, QUnit tests needs to be updated to test loading and running of projects/experiments.

- [x] Every test should create a new WebSocket connection, the tests should pass when running in parallel.
- [x] Restore all previously existing QUnit tests
- [x] Refactor the SimulationHandler so that it can be reused in the tests rather than having its code duplicated inside the tests
- [x] Add Qunit tests to check experiment activation / switching of active experiment
- [x] Add QUnit tests to cover the functionality for upload models to dropbox
- [x] Add QUnit tests to cover the functionality for upload simulation results to dropbox
- [x] Add QUnits test to cover download model results in DEFAULT format and in NEURON/NEUROML/LEMS format
- [x] Add QUnit test to cover download simulation results in both RAW and RECORDING format
- [x] Add to this list and make sure that every functionality that we currently have is covered by a test

**Comment by gidili** [comment]
@jrmartin reviewed the SimulationHandler refactoring - looking good!

One question, I noticed the new methods loadProject and loadExperiment are being now called in the tests and that's great - but createExperiment, playExperiment, persistProject, deleteExperiment among others not yet. 

Is this because we didn't have anything around that functionality in the tests? Meaning that once we add tests as per list above these are likely to get integrated?
