### ISSUE TITLE
QUnit tests split

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.frontend#327]
At the moment there is one file which defines multiple tests which have different requirements in terms of bundles deployed server side. At the very least we should have different files for the different configurations:

- [x] Tests for neuronal domain - GeppettoNeuronalTests.html 
- [x] Tests for neuronal simulations (require simulator.external) - GeppettoNeuronalSimulationTests.html
- [x] Tests for fluid dynamics - GeppettoFluidDynamicsTests.html
- [x] Tests for the persistence layer - GeppettoPersistenceTests.html
- [x] Core tests which don't require any of the above - GeppettoCoreTests.html
- [x] GeppettoTests Suite if QUnit allows it which runs all of them

Of course ideally we'd find a way for the differnet backend bundles to contribute QUnit Integration tests as there is no reason for the frontend to know about anything which is domain specific.

**Comment by gidili** [comment]
@jrmartin few questions (some of these may be work in progress in that case I apologize):

- GeppettoNeuronalSimulationTests.html is coming up blank for me?
- GeppettoNeuronalTests.html tests are failing, I thought we resolved the reset connection issue?
- GeppettoPersistenceTests.html I see stuff being plotted on top of the tests (I am assuming a simulation being replayed), is this desired and if so what is it testing to do with persistence?
- GeppettoFluidDynamicsTests.html this seems to run for a long time but never end... are you seeing the same?
- GeppettoAllTests.html - is the idea for this to become a simple page that links to the other test pages? Because at the moment I see tests in there too
