### ISSUE TITLE
Enable optional rendering of neurons as lines instead of cylinders and spheres

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.frontend#343]

**Comment by slarson** [comment]
Just throwing in some additional thoughts on this -- remember [this nifty demo](https://nxxcxx.github.io/Neural-Network/)?  Apparently rather than straight lines they use [CubicBezierCurves](https://github.com/nxxcxx/Neural-Network/blob/master/js/axon.js#L4).   Then, to give it the dynamic quality, it seems to [send particles along those curves](https://github.com/nxxcxx/Neural-Network/blob/master/js/signal.js).  I think it is a very interesting effect and it would be neat to play with as an alternate line mode... :candy:

**Comment by pgleeson** [comment]
@tarelli What are the console commands to make this switch?

**Comment by tarelli** [comment]
@pgleeson For now 

```
purkinje.setGeometryType("lines")
```
but finalyzing the API this week.

![screen shot 2015-10-05 at 11 03 36](https://cloud.githubusercontent.com/assets/81127/10277858/eaa7bf60-6b50-11e5-97b9-95e6268fe38c.png)
