### ISSUE TITLE
Extend Plotting Widget with axis unit

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.frontend#354]
E.g. Voltage (V), Time (s)

**Comment by gidili** [comment]
@tarelli @adrianq any idea why units are coming up as null? From live (HH sample):
<img width="855" alt="screenshot 2015-10-16 11 11 55" src="https://cloud.githubusercontent.com/assets/68134/10539351/ddbee3d8-73f6-11e5-960e-706bbd5176f7.png">

After looking around a bit I see that flot supports axis labelling, so that might do it. Currently trying to understand why units are empty and how to set axis labelling.

**Comment by tarelli** [comment]
@gidili might be a bug in that recording, is it the same with other models?

**Comment by gidili** [comment]
@tarelli here's the same from the C. elegans muscle cell:
<img width="958" alt="screenshot 2015-10-16 11 21 17" src="https://cloud.githubusercontent.com/assets/68134/10539539/11e39a0e-73f8-11e5-8dc2-383f137f25cd.png">

What's another good one to check?

**Comment by tarelli** [comment]
@gidili I think it's a bug of the print, do hhcell.electrical.SimulationTree.hhpop[0].v.getUnit()

**Comment by gidili** [comment]
@tarelli yeah that works, thanks!

**Comment by gidili** [comment]
OK report after looking at this all day: 

We were already including a [flot extension library to label axes](https://github.com/xuanluo/flot-axislabels/blob/master/jquery.flot.axislabels.js#L117) but not using it. 

Works ok when showing values on both axes:
<img width="647" alt="screenshot 2015-10-16 17 55 44" src="https://cloud.githubusercontent.com/assets/68134/10547912/29e1aa2e-742f-11e5-9911-22cfac6e336a.png">

There is a bug with the flot extension library we are using that makes it so that if we hide the axis (as in the case of the dynamic plot) the label gets positioned in the top left:
<img width="491" alt="screenshot 2015-10-16 18 05 08" src="https://cloud.githubusercontent.com/assets/68134/10548121/914c5da2-7430-11e5-8e9e-d945cf99351e.png">

We are not showing axis for the dynamic plot because the X values do not auto-update and it looks something like this:
<img width="505" alt="screenshot 2015-10-16 18 10 17" src="https://cloud.githubusercontent.com/assets/68134/10548245/308d1afa-7431-11e5-849f-82755fb2cccb.png">

Options I see:

1) Drop the extension library altogether and roll our own for labelling axes (kinda sucks because it works quite well when the axes are showing)
2) Modify the extension library to "fix" in the case of no axis displayed
3) In between, use the library if there's axis shown and roll our own if not (kinda sucks)
4) Figure out how to update the range step by step so that it doesn't show fixed values in the dynamic plot, and always show both axes

P.S. also will map symbols (V, s etc) to friendly strings at some stage, I am not worrying about that for now.

**Comment by gidili** [comment]
@tarelli @adrianq thoughts appreciated
