### ISSUE TITLE
Finalise multi-compartment simulation workflows

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.frontend#375]
- [x] Decide on instance path to reference a particular comparment
- [x] Add compartment type
- [x] Execute a simulation recording from all compartments
- [x] Define API to link membrane potential of different compartments to enable lighting up of the morphologies
- [ ] Document the API

**Comment by adrianq** [comment]
Closing this one....We can discuss what to document/test next week.

**Comment by pgleeson** [comment]
Just checking... has anyone actually rerun a simulation of a multicompartmental cell, where all the segments of the cell were coloured with the changing membrane potential? This is the more likely use case rather than plotting. This is a crucial test of this functionality, ideally for cells with 1000's of segments.

**Comment by adrianq** [comment]
I have tested for acnet... I would like to test it for CA1 asap
