### ISSUE TITLE
Refactor dependency management to use npm and webpack

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.frontend#494]
Once #493 is completed:

To do

@tarelli

- [x] Merge development into npmExperiment
   - [x] Update stackViewer widget @adrianq @tarelli
   - [x] Update plot.ly widget @adrianq @tarelli
- [x] Fix Collada loader
- [x] Review pom file. A bit refactor has been already made but to double check we are not doing anything we shouldn't be doing. Some already identified tasks are:
   - [x] node_modules are currently copied into the virgo server. This is unnecessary and what is more it makes everything much slower. @tarelli @adrianq
   - [x] Test if production profile mvn. Seems to be fine.. @tarelli 
   - [x] Review new pom in general: I have deleted requirejs-maven-plugin, . @tarelli 
   - [x] Review performance for regular mvn install @adrianq
- [x] There is this legendary [bit of code](https://github.com/openworm/org.geppetto.frontend/blob/development/src/main/webapp/js/GEPPETTO.js#L334-L373) that can be probably removed together with something else. @tarelli 
- [x] GeppettoVanilla refactor @tarelli 
- [x] Fix mvn install in travis. Tried this node_js: "5.12.0" but didn't work. @tarelli 
- [x] Three-js
This is the official three-js lib: https://www.npmjs.com/package/three
This is the one we are using with all addons inside but stil in 0.79: https://www.npmjs.com/package/three-js
As discussed, probably the best option is to moved to the official one but I believe it was a little bit tricky to have it working together with the addons [see thread on GH](https://github.com/mrdoob/three.js/issues/9562)
Also, to make it funnier, I haven't merged [all these changes](https://github.com/openworm/org.geppetto.frontend/commit/a8acefc26705242654cfe5f2febac646fc5f69be#diff-5f1d55a023e7c767225e8340713a5a76) and some other stuff may be broken. @tarelli I won't do this without you ;) @tarelli @gidili 
- [x] Migrate  OSB extensions to new architecture @tarelli

@gidili 

- [x] Migrate QUnit to npm. @gidili @adrianq 
- [x] Migrate Casper to npm. @gidili @adrianq 
- [x] Spotlight is showing up at the top and doesnt seem to work. AQ: Spotlight uses typeahead library. I changed it for jquery-typeahead and obviously it is not working. Will have a look. @gidili 
- [ ] Migrate  VFB extensions to new architecture. @gidili 

@adrianq 

- [x] Widgets: @adrianq
   - [x] Double check everything is working fine. I have done some dummy testing but it would be good to test them carefully.
   - [x] I have removed most of the stuff in every config.js for every widget and add it to the widget main class. There is just something about the register command (see sample) remaining there. I think we can extract these bits into a single file or something like this (it can not be moved inside the widgets as it needs to be executed even before a widget has even been initalised) and get rid of this annoying config.js
   - [x] Remove local dependencies (anchor and slick) in Popup widget
   - [x] TreeVisualiser using D3 is not working but not sure if we really want to fix it...
   - [x] Remove local dependencies (d3 and d3.hive) in Connectivity widgets
   - [x] Merge stack viewer @gidili @adrianq
- [x] Migrate  Default extensions to new architecture.
- [x] Implement a default mvn install profile where frontend stuff is bundled, no hot refresh for js/html frontend is expected.
- [x] Fix production profile mvn
- [x] The way we used to load extension is not working with npm. This ```if (extensionConfiguration[extension])``` in extensions.js is not evaluated properly by npm. Therefore, even when we have some extensions set to false. It will throw an error claiming the require can not be satisfied. 
- [x] Something to keep in mind: I have moved the Events inside [GeppettoEvents class](https://github.com/openworm/org.geppetto.frontend/blob/npmExperiments/src/main/webapp/js/GEPPETTO.Events.js#L46-L78). So now we will have to do Geppetto.Event.WinterIsComing instead of Event.WinterIsComing. I think I have changed to new format every single occurrence I could find in the code but have this in mind in case you catch an error that may have sth to do with events.
- [x] I have deleted a lib called rAF without consequences so far. @tarelli @gidili were we actually using it?
- [x] Fix a bunch of warnings:
![screenshot from 2016-10-27 01 14 36](https://cloud.githubusercontent.com/assets/6850223/19749750/6554d644-9be3-11e6-9582-0155c6251ef9.png)
- [x] Plots resizing is broken, throes an error inside flot (but I wouldn't worry too much about this as we are switching to plotly). AQ: I had a look at this problem, seems to be related with a conflict betweem a very old version of jquery.flot (we are still using the local js) and recent version of jquery (from npm). If plotly is an option in the short term I would wait for it instead of fixing this one.

**Comment by adrianq** [comment]
This could be a good reference: https://github.com/dhis2/app-skeleton

**Comment by adrianq** [comment]
Current work in progress can be found [in this branch](https://github.com/openworm/org.geppetto.frontend/tree/npmExperiments).

Instructions:
1.- If you are using Eclipse you will have to disable the automatic deploy for js. If you have enabled validation for js files, you will have to exclude the node_modules generated during the npm compilation. Otherwise, Eclipse gets frozen. Aptana plugin can also be a pain. Try to disable or uninstall if it is causing problems.. This will probably apply for any other IDE that performs js/html/css validation.
1.- Change branch https://github.com/openworm/org.geppetto.frontend/tree/npmExperiments
2.- If you mvn install the project and run your virgo server as usual you should be able to see a classic Geppetto at 8080. However you will not be able to change the code inside webapp as it has been bundled. You will have to mvn install every time you make a change.
3.- If you want to deal with the webapp content (changing js/html/css files or debugging), we will have to start a webpack server. Go to org.geppetto.frontend/src/main/webapp and executes (no sudo!):
```
npm install
npm run start. 
```
When you execute a mvn install to org.geppetto.frontend and npm install is executed in this folder so most of the times you can skip the first command.
If you go to localhost:8081/org.geppetto.frontend/ you can see what it looks like a regular Geppetto. Keep in mind the dashboard is still old-style so open a project to see if everything is working. If you didn't encounter any problem, you can start changing folder, js and debug. The webpack-dev-server we have just opened (by running npm run start) will detect any change in the sources and redeploy. Double check that Eclipse is not hot deploying anything for you or you will have the classic model exception in the browser.
You can debug without any problem in Chrome. However with Firefox you will see the bundle js file not the original sources. Firefox has not include support for .map files (what we use in order to link the bundle js with the original sources). The good new is that Firefox will include this feature in the next version.

Issues:
- [ ] Refactor tests (QUnit and casper). Probably a good to moment to rethink if we want to do any refactor on this area. This task requires at least:
   - [ ] Review path to dependencies and change if needed.
   - [ ] If there is any extra lib not already migrated. Add it to the package.json
   - [ ] Change vm templates.
   - [ ] Maybe add a new entry source in package.json
   - [ ] Stabs lib can not be found but there are plenty of them in npm. Best option probably to change it for a different one
- [ ] Migrate everything related to the dashboard. Probably a little bit of refactor will be needed.
- [ ] Review pom file. A bit refactor has been already made but to double check we are not doing anything we shouldn't be doing. Some already identified tasks are:
   - [ ] node_modules are currently copied into the virgo server. This is unnecessary and what is more it makes everything much slower.
   - [ ] Review Grunt tasks. These tasks convert the less files, generates the dist templates for production, etc. Some of these tasks can potentially be moved to webpack and eventually removed the grunt dependency. At the moment, the steps in master profile are: npm install, grunt, npm run build
We would like to have three different scenarios: production, developer not interested in pure frontend aspects and developer.
- [x] Implement a default mvn install profile where frontend stuff is bundled, no hot refresh for js/html frontend is expected.
- [x] Fix production profile mvn
- [ ] Review production and default npm bundle. At the moment, the two of them execute npm run build that generates a bundle js file which allows to see the sources. For production, we may want to uglify and potentially compress the sources.
- [ ] Test if production profile mvn. Seems to be fine..
- [ ] Review new pom in general: I have deleted requirejs-maven-plugin, . 
- [ ] The way we used to load extension is not working with npm. This ```if (extensionConfiguration[extension])``` in extensions.js is not evaluated properly by npm. Therefore, even when we have some extensions set to false. It will throw an error claiming the require can not be satisfied. 
- [ ] Widgets:
   - [ ] Double check everything is working fine. I have done some dummy testing but it would be good to test them carefully.
   - [ ] I have removed most of the stuff in every config.js for every widget and add it to the widget main class. There is just something about the register command (see sample) remaining there. I think we can extract these bits into a single file or something like this (it can not be moved inside the widgets as it needs to be executed even before a widget has even been initalised) and get rid of this annoying config.js
- [ ] There is this legendary [bit of code](https://github.com/openworm/org.geppetto.frontend/blob/development/src/main/webapp/js/GEPPETTO.js#L334-L373) that can be probably removed together with something else.
- [ ] Something to keep in mind: I have moved the Events inside [GeppettoEvents class](https://github.com/openworm/org.geppetto.frontend/blob/npmExperiments/src/main/webapp/js/GEPPETTO.Events.js#L46-L78). So now we will have to do Geppetto.Event.WinterIsComing instead of Event.WinterIsComing. I think I have changed to new format every single occurrence I could find in the code but have this in mind in case you catch an error that may have sth to do with events.
- [ ] Three-js
This is the official three-js lib: https://www.npmjs.com/package/three
This is the one we are using with all addons inside but stil in 0.79: https://www.npmjs.com/package/three-js
As discussed, probably the best option is to moved to the official one but I believe it was a little bit tricky to have it working together with the addons
Also, to make it funnier, I haven't merged [all these changes](https://github.com/openworm/org.geppetto.frontend/commit/a8acefc26705242654cfe5f2febac646fc5f69be#diff-5f1d55a023e7c767225e8340713a5a76) and some other stuff may be broken. @tarelli I won't do this without you ;)
- [ ] Most of the require are done using relative path except from geppetto. We may want to create some alias in webpack for the most usual ones.
- [ ] Plenty of loadCss functions everywhere, we may want to move them to a utils class
- [ ] I have refactored main.js and app.js quite a lot but I think it would be interesting a brief chat about how we want to organise these two files.
- [ ] I have deleted a lib called rAF without consequences so far. @tarelli @gidili were we actually using it?
- [ ] Fix a bunch of warnings:
![screenshot from 2016-10-27 01 14 36](https://cloud.githubusercontent.com/assets/6850223/19749750/6554d644-9be3-11e6-9582-0155c6251ef9.png)
.

cc @tarelli @gidili

**Comment by gidili** [comment]
@adrianq @tarelli tested the branch, looking great and very easy to put together with and without dev server. Was able to debug individual files with the dev server.

Only issues I saw:

- the spotlight is showing up at the top and doesnt seem to work 
- plots resizing is broken, throes an error inside flot (but I wouldn't worry too much about this as we are switching to plotly)

Other things I noticed:

- mvn install takes much longer every time as it does the webpacking every time, I guess we have to bite the bullet on this

**Comment by adrianq** [comment]
Thanks @gidili! I have updated the first comment with the issues you found out. Regarding the slow-down when mvn installing,  as you said, it is happening because I have added an extra step webpacking the web application folder.  Don't know exactly what to do with this issue. Let's discuss tomorrow!

**Comment by adrianq** [comment]
Tentative schema for the folder structure:
```
	webapp
		package.json	
		extensions
			package.json <- the current extensionsConfiguration.json
			geppetto-osb
				main.js <- extends from initialization.js			
				js
					tests
						geppetto-casper-osb.js
			geppetto-widget-3d
				package.json <- imports three.js, effectComposer.js, etc.			
				js
					sceneFactory.js
					sceneController.js			
			geppetto-widget-plotting
				package.json <- There is also metadata here, name, description, geppetto version?
				js <-Somewhere in there the code is telling Geppetto this is a widget
				less
			geppetto-component-query
				js
				less
				package.json
			geppetto-dashboard	
				templates
					dashboard.vm (probably not needed for the dashboard but in general an extension might define their template if it wants to?)
				model
					...
				controllers
					...
			geppetto-experiment-controls
			geppetto-experiment-table
			geppetto-jsconsole
		
		templates
			geppetto.vm
		less
			geppetto.less
		fonts
			font-awesome
			geppetto-font	
		images

		js	
			main.js (only one top level!)
			components
				extension.js ? any common API for all extensions?		
				initialization.js <- extends from extension.js	
				component.js <- common component API, extends from extension.js, e.g. setContainer(dialog or specific div)
				widget.js <- extends from component.js
				ui
					dialog.js <- APIs like setName, minimize, maximize, setPosition, hide, show
					modal.js	
			model
				node.js		
				type.js
				instance.js
				project.js
				experiment.js
				...
				factory
					modelFactory.js
					projectFactory.js				
			controllers			
				modelController.js
				experimentsController.js
				geppettoHandler.js
			tests
				geppetto-casper.js
		WEB-INF
```

**Comment by tarelli** [comment]
@adrianq @gidili moved to the top the todos and grouped by lead person for the changes, starting now to look at mines. I moved the (near) future stuff to a separate card https://github.com/openworm/org.geppetto.frontend/issues/515

**Comment by tarelli** [comment]
I had to move to Eclipse Neon (which requires Java8) for it to work, even following Adrian steps my old Eclipse kept crashing. Works seamlessly with Neon without changing any option.

**Comment by adrianq** [comment]
I have migrated connectivity widget to use npm dep and while doing it I have upgraded to the latest version (version 4). Plenty of things has changed in this new version especially in the force layout. This is the main reference I used to check what have changed:
https://github.com/d3/d3/blob/master/CHANGES.md
I have checked everything is working for the four layouts (force, chord, hive (I have to install another dep with d3-plugins) and matrices) but if you find any error have a look at the link afforementioned.

**Comment by adrianq** [comment]
I have deleted treevisualiserd3 widget. This widget hasn't worked for more than a year and although to migrate it to npm and d3 v4 should be quick once the connectivity widget has been migrated, to fix it  is probably a huge and nonsense task. What is more, d3 logic is not particularly interesting.

**Comment by tarelli** [comment]
![screen shot 2017-02-21 at 14 49 48](https://cloud.githubusercontent.com/assets/81127/23169811/0d144906-f845-11e6-8aad-315b15d0b3e4.png)

**Comment by adrianq** [comment]
I have moved the investigation about having a package.json per widget to phase II
