### ISSUE TITLE
Add StackViewer widget

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.frontend#501]
- [x] Wrap as a widget
- [x] Develop basic functionality
- [x] Add API to addSlice(instance)
- [x] Add API to addData([instances])
- [x] Add API to removeSlice(instance)
- [x] Add API to setColour(instance, color)
- [x] Listen to remove instance event
- [x] Configurable event handlers for handling events
- [x] Listen to colour change events
- [x] Listen to selection events
- [ ] Polish up
- [ ] Add documentation
- [x] Merge to development

**Comment by Robbie1977** [comment]
@tarelli @gidili Any idea why either
```GEPPETTO.ModelFactory.getAllVariablesOfMetaType(VFB_00000001.getType().VFB_00000001_slices, 'ImageType')
GEPPETTO.ModelFactory.getAllVariablesOfType(VFB_00000001.getType().VFB_00000001_slices, 'ImageType')```
returns an empty list?
FYI: VFB_00000001.VFB_00000001_slices is undefined.

Need to able to find all VFB_xxxxxxxx.VFB_xxxxxxxx_slices and extract the data variable from them.

**Comment by gidili** [comment]
@Robbie1977 no idea - I'll have a look asap. Weird about that _slices instance being undefined. Last time I checked it was there (after doing getInstance for that very same path).

**Comment by gidili** [comment]
@Robbie1977 first glance the _slices instance seems to be there after you do getInstance (and passed into the stackWidget by that addStackWidget function):

<img width="848" alt="screenshot 2016-10-14 22 55 30" src="https://cloud.githubusercontent.com/assets/68134/19403822/9d3ade68-9261-11e6-8626-0401b0e2a27d.png">

Also that getAllVariablesOfMetaType method takes a list of types as the first parameter  in the signature (you're passing an instance):

`getAllVariablesOfMetaType: function (typesToSearch, metaType)`

It's meant as a way to look inside composite types for variables of particular metatypes, below an example of how we use it to find 'ImageType' in the control panel for the image column:

`GEPPETTO.ModelFactory.getAllVariablesOfMetaType($entity$.$entity$_meta.getType(), 'ImageType')[0].getInitialValues()[0].value.data`

**Comment by gidili** [comment]
@Robbie1977 once the instance is there, to get the variable should be simply:

`VFB_00000001.VFB_00000001_slices.getVariable()`

Once it's passed to the stack widget the instance will be there because we are calling getInstance in the addStackWidget helper method. 

To get values out of the variable we need @tarelli's help.

**Comment by tarelli** [comment]
@gidili @Robbie1977 The value was missing, added now, to retrieve it same .getInitialValues() as always.

**Comment by Robbie1977** [comment]
Can get the data now but still not directly via VFB_00000001.VFB_00000001_slices.getVariable().getInitialValues()

VFB_00000001.VFB_00000001_slices is undefined

VFB_00000001.getVariable().VFB_00000001.VFB_00000001_slices.getInitialValue().value.data works

**Comment by gidili** [comment]
@Robbie1977 getInstance will create the instance given a potential instance path: 

`Instances.getInstance('VFB_00000001.VFB_00000001_slices')`

After that the instance will be there. 

In the addStackWidget globally exposed method (in the VFB components initialisation extension) we do just that, so that everything that all potential instances ending with '_slices' get created and passed to the stackWidget:

```
            window.addStackWidget = function(){
                var potentialInstances = GEPPETTO.ModelFactory.getAllPotentialInstancesEndingWith('_slices');
                var sliceInstances = [];
                for(var i=0; i<potentialInstances.length; i++){
                    sliceInstances.push(Instances.getInstance(potentialInstances[i]));
                }

                G.addWidget(8).setData({
                    instances: sliceInstances
                });
            };
```

**Comment by gidili** [comment]
@tarelli @Robbie1977 I think this is in pretty good shape now! 

Minor things that I can see as outstanding:
- [ ] buttons at the top to go inside canvas
- [ ] zooming / resizing widget causes problems with plane resizing/positioning on the 3D scene
-  [ ] Need to factor out some vfb domain specific defaults (getInitialState of the StackViewerComponent) so that they are passed via configuration

Also not as minor, we need to make some changes to generalize for potentially having multiple stack widgets:
 -  [ ] listeners are currently outside the component, causing us to maintaining a reference to widget names in the configuration - if they were to be moved inside the components each widget would take care of its own stuff and a lot of code would disappear from config and we would not have to keep track of how many stack widgets we have.  
 - [ ] upon opening additional stack widgets and passing down empty list of instances, the canvas contents seem to be shared still, indicating some global PIXI renderer is probably being re-used across widget instances
 - [ ] upon opening additional stack widgets, navigating the stack with mouse wheel functionality seems to be lost

**Comment by tarelli** [comment]
@Robbie1977 @gidili I plan to merge this branch back to development on Wednesday, let me know if you think that's a problem!

**Comment by gidili** [comment]
@Robbie1977 fine by me if it's fine with @Robbie1977!

**Comment by Robbie1977** [comment]
I'm happy with the warning will add load to basic build until npm is implemented.

**Comment by tarelli** [comment]
@Robbie1977 @gidili is browser.min.js needed? It's 1.4MB

**Comment by Robbie1977** [comment]
Suspect not anymore but trying to test but frontend build is broken at sec so will let you know when it's back.

**Comment by tarelli** [comment]
Alright it's merged. Waiting for documentation to close this one, would be good to add it both to the inline one and docs.geppetto.org.
