### ISSUE TITLE
Popup widget directional nav buttons do the same.

### ISSUE THREAD

**Issue by Robbie1977** [openworm/org.geppetto.frontend#537]
The 'back' and 'forward' controls both scroll through the history in the same order.

**Comment by gidili** [comment]
@Robbie1977 from what I recall they're supposed to "loop" (instead of figuring out whats the first/last element and stopping there) so this can get a bit confusing. There was also the complication that when you navigate history that element you just visited becomes the "latest" in history, which makes the buttons behave in a way quite different from browser back/forward buttons... more like an infinite loop 😂  I think we do need to revisit that logic a bit.

**Comment by Robbie1977** [comment]
If you have a history list of multiple items both buttons cycle through them in the same order.

**Comment by gidili** [comment]
@Robbie1977 alright then needs to be fixed! Should be a quick one 👍
