### ISSUE TITLE
Results list scrolling

### ISSUE THREAD

**Issue by Robbie1977** [openworm/org.geppetto.frontend#538]
The scrolling bar jumps back and forth making it almost impossible to scroll to the end of a long results list. see video: https://youtu.be/9FEkreR_pmA

**Comment by tarelli** [comment]
@Robbie1977 that feature is called infinite scrolling, things keep appearing because it's not really the end and more results get loaded as you scroll down. The loading only on scrolling down is an optimisation to visualise large lists of results as it would be impractical to load everything at the beginning so more results are effectively loaded on demand. The alternative of that would be pagination.

**Comment by tarelli** [comment]
http://griddlegriddle.github.io/Griddle/infiniteScroll.html

**Comment by Robbie1977** [comment]
Just doesn't work well with our row height - makes it quite difficult to figure out where you are. Think we might have to go with pagination

**Comment by tarelli** [comment]
We could make it an option to be chosen in the extensions then.

**Comment by gidili** [comment]
The thicker the rows the harder it becomes to use. We can try navigation and see if that's better. Should be a quick change to propagate a property from the control panel to the griddle component we are using.

**Comment by gidili** [comment]
@Robbie1977 @tarelli experimented a bit with this and enabled optional pagination on the query results (available on development branch https://github.com/openworm/org.geppetto.frontend/commit/b781446636e4944b0e560f12da6137364910d00f), it looks like this:

![screenshot 2017-01-23 10 36 57](https://cloud.githubusercontent.com/assets/68134/22201383/35aea3c6-e15b-11e6-81c4-48ea82c38520.png)

And you enable it like this:
![screenshot 2017-01-23 11 01 32](https://cloud.githubusercontent.com/assets/68134/22201400/51fc83e0-e15b-11e6-94c7-3db56e5d83dd.png)

Filter works and it will paginate only results that match that filter. You can fit 3 maybe 4 results per page right now but no more because Geppetto doesn't scroll. 

What could be done with more work is to instrument the query result component with its own scrollbar... but scrollbars are dangerous territory as we have learned 😂
