### ISSUE TITLE
Once item with visual type is deleted in control panel it can't be re-added to scene

### ISSUE THREAD

**Issue by Robbie1977** [openworm/org.geppetto.frontend#541]
Once items are deleted this seems to break all normal methods of adding to scene via spotlight or links.

Seems to also affect previously un-added items.

**Comment by gidili** [comment]
@Robbie1977 does this mean nothing can be added to the scene? Any console errors?

**Comment by Robbie1977** [comment]
yes nothing with no errors. 

To recreate: 

Open: http://vfbsandbox.inf.ed.ac.uk:8180/org.geppetto.frontend/geppetto?load_project_from_url=http://vfbsandbox.inf.ed.ac.uk/do/geppettoJson.json?i=VFB_00000001,VFBd_00100049%26t=VFBt_001%26d=

open control panel,
delete anything,
open spotlight,
enter 'VFB_00000002 (fru-M-200267)' (not in previous scene)
add to scene does nothing (fly doesn't rotate)

**Comment by gidili** [comment]
@Robbie1977 got it I can see it too. Will take a look!

**Comment by gidili** [comment]
@Robbie1977 there is a fix for this on development + geppetto-vfb extension development branch. I also did some refactoring on components initialization to make it easier to debug and make those js strings much shorter wherever we are using fetch variable. It was due to something we introduced in a branch that was merged into development last week. 

If you can confirm it's back to working we can close 👍

**Comment by gidili** [comment]
🎊  :champagne:
