### ISSUE TITLE
Migrate Jupyter infrastructure to npm

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.frontend#566]

**Comment by adrianq** [comment]
GeppettoJupyter code has been already merged with npmExperiment branch in org.geppetto.frontend. Eventually, it will get into development and master branch. I have created a npmExperiment branch for NEURON-UI, org.geppetto.jupyter and neuron extension. However, this work is not finished yet. Bits currently missing:
- [ ] Modify install and update script to execute everything that is needed. At the moment in order to make it work npm install and npm run build-dev --contextPath=org.geppetto.frontend --useSsl=false --embedded=false --embedderURL=/ needs to be executed manually in the webapps folder
- [ ] node_modules are being copied and this makes everything much slower. Try to copy just the compulsory stuff
- [ ] Try to find a way that allows development without waiting long time. pip with -e flag sounds like a sensible option but further investigation is needed.
- [ ] Migrate anything develops from this date from development into the npmExperiment

**Comment by borismarin** [comment]
Ow, I'd give my kingdom for a recording of matteo ranting against npm some
years ago, when someone at a gpt meeting first suggested using it...

2017-06-20 11:43 GMT-03:00 Matteo Cantarelli <notifications@github.com>:

**Comment by gidili** [comment]
Life comes at you fast
