### ISSUE TITLE
Missing tooltip / titles on control buttons

### ISSUE THREAD

**Issue by Robbie1977** [openworm/org.geppetto.frontend#592]
I'm adding title text to the buttons but they get regenerated at various sections so probably needs to be added into the generation code.

Here is my current labels:
```
            $('#queryBuilderBtn').first().title="Query Builder";
            $('#controlPanelBtn').first().title="Control Panel";
            $('#spotlightBtn').first().title="Search";
            $('#panLeftBtn').first().title="Pan Left";
            $('#panUpBtn').first().title="Pan Up";
            $('#panRightBtn').first().title="Pan Right";
            $('#panDownBtn').first().title="Pan Down";
            $('#panHomeBtn').first().title="Reset to Home Position";
            $('#rotateLeftBtn').first().title="Rotate Left";
            $('#rotateUpBtn').first().title="Rotate Up";
            $('#rotateRightBtn').first().title="Rotate Right";
            $('#rotateDownBtn').first().title="Rotate Down";
            $('#rotateBtn').first().title="Rotate the scene";
            $('#zoomInBtn').first().title="Zoom In";
            $('#zoomOutBtn').first().title="Zoom Out";
```

**Comment by gidili** [comment]
@Robbie1977 yes they need to be added in the component that renders them, for example camera controls is [here](https://github.com/openworm/org.geppetto.frontend/blob/development/src/main/webapp/js/components/interface/cameraControls/CameraControls.js#L95), while foreground control buttons are [here](https://github.com/openworm/org.geppetto.frontend/tree/development/src/main/webapp/js/components/interface/foregroundControls/buttons), so it's just a matter of adding the attribute there in the component. Those labels are generic enough that I think it's fine to just apply them for everything, if we wanted to have different labels we'd have to pass down as props when the component gets created, doable but maybe overkill since these labels look fine.

**Comment by Robbie1977** [comment]
working in query branch
