### ISSUE TITLE
Scroll on long query results causing stability issues

### ISSUE THREAD

**Issue by Robbie1977** [openworm/org.geppetto.frontend#619]
Scrolling on a long list is causing a cache of superseded mouse events to get created that then lock up the DOM.   

Below is a video showing how the events continue indefinitely after any user input preventing further interaction:

https://youtu.be/rHuOfcOiZ8Q

**Comment by gidili** [comment]
@Robbie1977 did we not introduce pagination to avoid trouble with the infinite scroller? That's all griddle logic, the only solution is to try an upgrade to the latest griddle that is now on 1.x (we are 0.6, tried an upgrade to 0.7 and 0.8 but there were breaking changes). It's a big job though as a lot has changed but I was reading infinite scrolling was improved.

**Comment by Robbie1977** [comment]
https://v2a.virtualflybrain.org/?id=VFB_00011403&i=VFB_00017894,VFB_00011403 

Select neuron and then select query for find similar.

Only 7 results but can't scroll to the bottom with mouse-wheel!? (locks after a few turns)

**Comment by gidili** [comment]
@Robbie1977 this was never resolved and one of the reasons we switched to pagination if you remember... it's unfortunately a griddle bug (the grid we are using), I saw it reported on their github a number of times and reported it myself. They never fixed it and they are pointing people to newer versions. I suspect the only solution is to attempt a migration to griddle 1.x, which is doable but a significant task because they changed a lot of stuff.

**Comment by Robbie1977** [comment]
@tarelli This is also an issue with the control panel with more than 1 page of data. @gidili I'm assuming this is still an issue in the latest release?

**Comment by tarelli** [comment]
We started using pagination since griddle has quite few problems with infinite scrolling, see open issues https://github.com/GriddleGriddle/Griddle/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20infinite Something to check in the latest Griddle if it's still a problem but as Gio points out above it's probably going to be a significant task.

**Comment by Robbie1977** [comment]
@gidili @jrmartin Latest version seems to have an issue when you reach the bottom of the list: 
https://youtu.be/Cq-oURi_-3Y
Seems to get itself stuck changing the table size without affecting the visible table so I'm guessing it's removing the top (out of sight) rows but this is then triggering some scroll preloading to re-add them.

**Comment by gidili** [comment]
@Robbie1977 seems fixable based on what we have improved so far. 

Besides that, finding it better in general? In my test it was far more usable but I didn't see the issue when getting to the bottom of the query results or the control panel - maybe I didn't have enough results.

**Comment by Robbie1977** [comment]
@gidili @jrmartin Can't get the error on Chrome anymore - will monitor it but seems the pixies have fixed it for us.

**Comment by gidili** [comment]
@Robbie1977 this pleases me greatly 😄
