### ISSUE TITLE
"add to plot" broken in control panel

### ISSUE THREAD

**Issue by mattearnshaw** [openworm/org.geppetto.frontend#694]
not getting a context menu with the "Add to Plot…" button, it's just a [NOP](https://en.wikipedia.org/wiki/NOP). also the icon appears squashed. had a brief look but not seeing the problem immediately… @gidili ?

**Comment by gidili** [comment]
@mattearnshaw weird, I can have a look. Development I assume?

**Comment by mattearnshaw** [comment]
@gidili yeah, development or vfb-8/17

**Comment by jrmartin** [comment]
The issue here is that the menu items, which are used inside the MenuButton to populate the drop down menu,  are expected to be inside props.configuration.menuItems, but are now stored in a PromisedValue array as seen in this screenshot.

A fix could be to look inside the PromisedValue array if props.configuration.menuItems is empty

![no menutiems](https://user-images.githubusercontent.com/4562825/31825220-57b8b6c0-b566-11e7-82c8-9acb23ac324a.png)

**Comment by gidili** [comment]
Thanks @jrmartin! I think we might need to have to add a .then somewhere - any ideas @tarelli? 

I am surprised that those values are in a promise since it's simply parameters that are passed via react props?

**Comment by tarelli** [comment]
Yeah, weird, I wouldn't have expected them to be, I need to look at the code, good catch @mattearnshaw!

**Comment by mattearnshaw** [comment]
here's one solution using the `react-promise` module
https://github.com/openworm/org.geppetto.frontend/commit/0b5aa4991778a4a98ccaacb6bab22694c1c02058

if that looks OK then I can open a PR. you can probably do it without the additional module, but I'm not sure how…

**Comment by gidili** [comment]
@mattearnshaw I think there's another fix for that already in another branch from @jrmartin, here's the commit --> https://github.com/openworm/org.geppetto.frontend/commit/1ae4f162189a2e5c76a57a24b1bc16ae732e9f5e

Both fixes are interesting. @tarelli what do you think?
