### ISSUE TITLE
Query: Number of rows increasing during clear of query results causing instability.

### ISSUE THREAD

**Issue by Robbie1977** [openworm/org.geppetto.frontend#766]
To recreate:
Add a long query result.
Note: number of TR rows only those displayed not the full results 
Open another query.
Note: Number of TR rows starts growing one at a time (slowly).

I suspect this is due to a clearing function accidentally triggering creation or hidden rows merely to clear them.

**Comment by Robbie1977** [comment]
This seems to be the culprit: https://github.com/openworm/org.geppetto.frontend/blob/development/src/main/webapp/js/components/interface/query/query.js#L33

**Comment by Robbie1977** [comment]
Specifically: https://github.com/openworm/org.geppetto.frontend/blob/development/src/main/webapp/js/components/interface/query/query.js#L78

**Comment by Robbie1977** [comment]
Begining to suspect it's creating new records but appears to work differently than on the first load?

FYI test on http://v2.virtualflybrain.org select medulla; list all images of neurons in (unclustered) then close and click on a 'synaptic terminal in' query.

**Comment by gidili** [comment]
@Robbie1977 Thanks for investigating this! 

As a recap .clearAllQueryItems on [L899](https://github.com/openworm/org.geppetto.frontend/blob/development/src/main/webapp/js/components/interface/query/query.js#L899) is what triggers that clear on [L78](https://github.com/openworm/org.geppetto.frontend/blob/development/src/main/webapp/js/components/interface/query/query.js#L78), that then triggers the notify changes on [L34](https://github.com/openworm/org.geppetto.frontend/blob/development/src/main/webapp/js/components/interface/query/query.js#L34). All that clear does is empty the list of query items in the query builder and then trigger a re-render of the component that has been registered as the callback when changes are notified ([L1350](https://github.com/openworm/org.geppetto.frontend/blob/development/src/main/webapp/js/components/interface/query/query.js#L1350) / [L1357](https://github.com/openworm/org.geppetto.frontend/blob/development/src/main/webapp/js/components/interface/query/query.js#L1357)) so that now the query builder is empty. It *should* not do anything with query results, that in fact should still be there unchanged after you call .clearAllQueryItems on the query component (I just tried to run a couple of queries then manually call that method and the query builder is clean and the results are still there unchanged as expected). 

This problem with rows created (god knows what griddle is doing behind the scenes) could indeed be what causes the browser to freeze but what I do not understand is why the freezing happens only when triggering the same queries - that work fine from the query builder - from term info links as the clear functionality is the exact same. 

Given what I am seeing I have to guess that this is some issue with the way react/griddle re-renders that in one case (manual query from query builder) does not cause freezing problems while in the other (programmatic) does. The only difference between the two cases that I can think of is timing, because in the programmatic option we clear then add stuff again and it might be all happening too fast and causing the problem. My intuition from seeing problems like this before on re-render tells me this could be resolved with a setTimeout (or more) in the right place.

I would say this is anywhere in between 1 and 3 days worth of debugging and trying to switch things around to get to the bottom of it.

**Comment by tarelli** [comment]
From Robb: If you clear the data out of the query builder it goes mental, workaround is to clear the data while things are on screen not clear though why it happens
