### ISSUE TITLE
Extend plot widget

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.frontend#769]

**Comment by mattearnshaw** [comment]
with regards the refactor, the basic problem is that plot is currently very tied into x-y timeseries and this problem is already apparent with how treatment of function plotting is bolted on (e.g. the ad-hoc `.isFunctionNode`/`.hasXYData`/`.hasStandardPlotData`), but now that we're wanting scatter plots, heatmaps etc. and we want them to be animated, the "contradiction" is ripening

- [ ] rather than distinguish between static (functions) and dynamic (animatable timeseries) plots, instead `updateDataSet` (which needs a better name, related to time) should call a function (given to the plot constructor) which returns what constitutes a slice of its data at a timestep. Then static plots are just defined by an identity function (they show the same thing at each step: I assume `plotly.animate` optimizes this away but otherwise we can do that)

- [ ] `updateXAxisRange`, `removeDataSet` appear to be unused

- [ ] …

**Comment by gidili** [comment]
From having tried (and failed) to shoehorn a scatterplot in there, I am starting to think that it wouldn't be such a bad thing is for non x-y based specialized plots (scatter-3d, raster, heatmap) we have separate specialised widgets. Adding that functionality to the existing plot widget is likely to turn into a nightmare (knowing the nuances of all the stuff we have in there).

**Comment by mattearnshaw** [comment]
I think it's possible to have an abstract core plot widget (based on retaining `plotGeneric`, which is what I'm using for our new heatmap/scatter plots) of which specialized plots are instances

**Comment by gidili** [comment]
@mattearnshaw yes, that would be ideal! If we can have that shared logic abstracted away somewhere and then the plotting options and various nuances (to do with margins and god knows what else) are specific for each specialised plot

**Comment by tarelli** [comment]
Still relevant, @mattearnshaw how's this going?
